spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: <cid>
            client-secret: <csecr>
  data:
    cassandra:
      keyspace-name: main
      username: <uname>
      password: <pwd>
      schema-action: create-if-not-exists
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s

datastax.astra:
  secure-connect-bundle: file:./src/main/resources/secure-connect-allbookslibrary.zip
